[package]
name = "advent-of-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
dialoguer = "0.8.0"
minisat = "0.4.4"
itertools = "0.10.1"
nom = "6.2.1"